set_property PACKAGE_PIN V17 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property PACKAGE_PIN V16 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property PACKAGE_PIN W16 [get_ports C]
set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property PACKAGE_PIN W17 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports {I[2]}]
set_property PACKAGE_PIN E19 [get_ports {I[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I[1]}]
set_property PACKAGE_PIN U16 [get_ports {I[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I[0]}]

set_property PACKAGE_PIN U19 [get_ports {I[2]}]
